// Generated by scripts/sync-codex-apps.mjs. Do not edit manually.

export type AppProject = {
  title: string;
  eyebrow: string;
  status: string;
  date: string;
  href: string;
  image: string;
  accent: string;
  summary: string;
  stats: Array<{ label: string; value: string }>;
  highlights: string[];
};

export const appProjects: AppProject[] = [
  {
    "title": "Job Hunt Tracker",
    "eyebrow": "Personal workflow",
    "status": "Live demo",
    "date": "Started July 29, 2026",
    "href": "/apps/job-hunt-tracker/index.html",
    "image": "/apps/job-hunt-tracker/preview.png",
    "accent": "teal",
    "summary": "A beginner-friendly portfolio project for tracking job applications, interview progress, contacts, and next steps.",
    "stats": [
      {
        "label": "Applications",
        "value": "6"
      },
      {
        "label": "Interviewing",
        "value": "1"
      },
      {
        "label": "Offers",
        "value": "1"
      }
    ],
    "highlights": [
      "View all applications in one table",
      "Filter applications by status",
      "Search by company, role, location, contact, or source"
    ]
  },
  {
    "title": "Support Ticket System",
    "eyebrow": "Internal tool",
    "status": "Live demo",
    "date": "Started July 29, 2026",
    "href": "/apps/support-ticket-system/index.html",
    "image": "/apps/support-ticket-system/preview.png",
    "accent": "coral",
    "summary": "A beginner-friendly portfolio project for triaging customer requests, priorities, ownership, and ticket status.",
    "stats": [
      {
        "label": "Open",
        "value": "2"
      },
      {
        "label": "Urgent",
        "value": "1"
      },
      {
        "label": "Resolved",
        "value": "2"
      }
    ],
    "highlights": [
      "View all support tickets",
      "Filter tickets by status and priority",
      "Search by title, requester, assignee, channel, or notes"
    ]
  }
];
